package sistemasoperativos1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import CoreV2.Proceso;

/**
 *
 * @author juanr
 */
public class ProcesoBloqueGUI extends javax.swing.JPanel {

    /**
     * Creates new form ProcesoBloqueGUI
     */
    public ProcesoBloqueGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(150, 100));
        setMinimumSize(new java.awt.Dimension(150, 100));
        setPreferredSize(new java.awt.Dimension(150, 100));
        setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ID: ");
        add(jLabel1);

        lblId.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 51, 51));
        add(lblId);

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre:");
        add(jLabel2);

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        add(lblNombre);

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PC:");
        add(jLabel4);

        lblPc.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblPc.setForeground(new java.awt.Color(51, 51, 51));
        add(lblPc);

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("MAR:");
        add(jLabel6);

        lblMar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblMar.setForeground(new java.awt.Color(51, 51, 51));
        add(lblMar);

        jLabel9.setBackground(new java.awt.Color(204, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Status:");
        add(jLabel9);

        lblStatus.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        add(lblStatus);

        jLabel11.setBackground(new java.awt.Color(204, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Tipo:");
        add(jLabel11);

        lblTipo.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(51, 51, 51));
        add(lblTipo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPc;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables

    public void setProcesoData(Proceso proceso) {
        if (proceso != null) {
            lblId.setText(String.valueOf(proceso.getId()));
            lblNombre.setText(proceso.getNombre());
            lblPc.setText(String.valueOf(proceso.getProgramCounter()));
            lblMar.setText(String.valueOf(proceso.getMemoryAddressRegister()));
            lblStatus.setText(proceso.getEstado().toString());
            lblTipo.setText(proceso.getTipo().toString());
        } else {
            // Poner valores por defecto si el proceso es null
            lblId.setText("N/A");
            lblNombre.setText("N/A");
            lblPc.setText("N/A");
            lblMar.setText("N/A");
            lblStatus.setText("N/A");
            lblTipo.setText("N/A");
        }
    }

}

