/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasoperativos1;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import CoreV2.SimConfig;
import CoreV2.OperatingSystem; 
import CoreV2.Proceso; 
import CoreV2.Cola; 
import CoreV2.AlgorithmsStrategies.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;


/**
 *
 * @author juanr
 */
public class SimuladorGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SimuladorGUI.class.getName());
    
    private OperatingSystem so;
    
    /**
     * Creates new form SimuladorGUI
     */
public SimuladorGUI(OperatingSystem so) {
        initComponents();
        this.so = so;
        
        boolean ioInicial = comboTipo.getSelectedItem().equals("I/O bound");
        spinnerCiclosExcepcion.setEnabled(ioInicial);
        spinnerCiclosSatisfacer.setEnabled(ioInicial);
        cargarConfiguracion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Simulador = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spinnerInstrucciones = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spinnerCiclosExcepcion = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinnerCiclosSatisfacer = new javax.swing.JSpinner();
        btnCrearProceso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboPolitica = new javax.swing.JComboBox<>();
        btnGuardarCambios = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblRelojGlobal = new javax.swing.JLabel();
        btnGuardarDefaultsProceso = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCpuProceso = new javax.swing.JLabel();
        lblCpuID = new javax.swing.JLabel();
        lblCpuPC = new javax.swing.JLabel();
        lblCpuMAR = new javax.swing.JLabel();
        lblCpuStatus = new javax.swing.JLabel();
        lblCpuTipo = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaListos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaBloqueados = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTerminados = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        Configuracion = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        spinnerDuracionCiclo = new javax.swing.JSpinner();
        btnAplicarDuracion = new javax.swing.JButton();
        Graficos = new javax.swing.JPanel();
        panelGrafico = new javax.swing.JPanel();
        Estadisticas = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblStatsTotales = new javax.swing.JLabel();
        lblStatsIOBound = new javax.swing.JLabel();
        lblStatsCPUBound = new javax.swing.JLabel();
        lblStatsCicloActual = new javax.swing.JLabel();
        lblStatsThroughput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new java.awt.BorderLayout());

        nombre.setText("Nombre");

        txtNombre.setToolTipText("Ingrese nombre del proceso");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Cant. Instrucciones");

        jLabel2.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU bound", "I/O bound", " " }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciclos para generar Excepcion");

        jLabel4.setText("Ciclos para Satisfacer Excepción:");

        btnCrearProceso.setText("Crear Proceso");
        btnCrearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProcesoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cambiar Política de Planificación");

        comboPolitica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "Round Robin", "SPN", "SRT", "HRRN", "Feedback" }));

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciclo de reloj Global");

        lblRelojGlobal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblRelojGlobal.setText("0");

        btnGuardarDefaultsProceso.setText("Guardar Default");
        btnGuardarDefaultsProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDefaultsProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzquierdoLayout = new javax.swing.GroupLayout(panelIzquierdo);
        panelIzquierdo.setLayout(panelIzquierdoLayout);
        panelIzquierdoLayout.setHorizontalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdoLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(nombre))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(comboPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel6))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblRelojGlobal))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(spinnerCiclosExcepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelIzquierdoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(spinnerCiclosSatisfacer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIzquierdoLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(btnCrearProceso))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2))
                            .addComponent(spinnerInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIzquierdoLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnGuardarDefaultsProceso)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelIzquierdoLayout.setVerticalGroup(
            panelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdoLayout.createSequentialGroup()
                .addComponent(nombre)
                .addGap(12, 12, 12)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerCiclosExcepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerCiclosSatisfacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboPolitica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRelojGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarDefaultsProceso)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jPanel5.add(panelIzquierdo, java.awt.BorderLayout.LINE_START);

        jLabel10.setText("CPU 1");

        jLabel11.setText("Proceso en Ejecución:");

        jLabel12.setText("ID: ");

        jLabel13.setText("PC: ");

        jLabel14.setText("MAR:");

        jLabel15.setText("Status:");

        jLabel16.setText("Tipo:");

        lblCpuProceso.setText("N/A");

        lblCpuID.setText("N/A");

        lblCpuPC.setText("N/A");

        lblCpuMAR.setText("N/A");

        lblCpuStatus.setText("N/A");

        lblCpuTipo.setText("N/A");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCpuProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(32, 32, 32))
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDerechoLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCpuID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelDerechoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCpuPC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(panelDerechoLayout.createSequentialGroup()
                        .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCpuTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDerechoLayout.createSequentialGroup()
                                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelDerechoLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCpuStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelDerechoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCpuMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblCpuProceso))
                .addGap(29, 29, 29)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblCpuID))
                .addGap(29, 29, 29)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblCpuPC))
                .addGap(33, 33, 33)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblCpuMAR))
                .addGap(34, 34, 34)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblCpuStatus))
                .addGap(42, 42, 42)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblCpuTipo))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jPanel5.add(panelDerecho, java.awt.BorderLayout.LINE_END);

        jLabel7.setText("Colas De Listos");

        areaListos.setEditable(false);
        areaListos.setColumns(20);
        areaListos.setRows(5);
        jScrollPane1.setViewportView(areaListos);

        jLabel8.setText("Cola de Bloqueados");

        areaBloqueados.setEditable(false);
        areaBloqueados.setColumns(20);
        areaBloqueados.setRows(5);
        jScrollPane2.setViewportView(areaBloqueados);

        jLabel9.setText("Cola de Terminados");

        areaTerminados.setEditable(false);
        areaTerminados.setColumns(20);
        areaTerminados.setRows(5);
        jScrollPane3.setViewportView(areaTerminados);

        jLabel23.setText("Log de Eventos:");

        areaLog.setEditable(false);
        areaLog.setColumns(20);
        areaLog.setRows(5);
        jScrollPane4.setViewportView(areaLog);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(285, 285, 285))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(278, 278, 278))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(295, 295, 295))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel7)
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPanel5.add(panelCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout SimuladorLayout = new javax.swing.GroupLayout(Simulador);
        Simulador.setLayout(SimuladorLayout);
        SimuladorLayout.setHorizontalGroup(
            SimuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SimuladorLayout.setVerticalGroup(
            SimuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Simulador", Simulador);

        jLabel22.setText("Duracion de Ciclo (ms)");

        spinnerDuracionCiclo.setModel(new javax.swing.SpinnerNumberModel(500, 10, 5000, 50));

        btnAplicarDuracion.setText("Aplicar Duración");
        btnAplicarDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfiguracionLayout = new javax.swing.GroupLayout(Configuracion);
        Configuracion.setLayout(ConfiguracionLayout);
        ConfiguracionLayout.setHorizontalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAplicarDuracion)
                    .addComponent(spinnerDuracionCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(801, Short.MAX_VALUE))
        );
        ConfiguracionLayout.setVerticalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerDuracionCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAplicarDuracion)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuracion", Configuracion);

        panelGrafico.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout GraficosLayout = new javax.swing.GroupLayout(Graficos);
        Graficos.setLayout(GraficosLayout);
        GraficosLayout.setHorizontalGroup(
            GraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraficosLayout.createSequentialGroup()
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        GraficosLayout.setVerticalGroup(
            GraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraficosLayout.createSequentialGroup()
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Graficos", Graficos);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas Generales"));

        jLabel17.setText("Procesos Totales Terminados:");

        jLabel18.setText("Procesos I/O Bound Terminados:");

        jLabel19.setText("Procesos CPU bound Terminados:");

        jLabel20.setText("Ciclo Actual:");

        jLabel21.setText("Throughput General:");

        lblStatsTotales.setText("0");

        lblStatsIOBound.setText("0");

        lblStatsCPUBound.setText("0");

        lblStatsCicloActual.setText("0");

        lblStatsThroughput.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatsTotales))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatsIOBound)))
                .addGap(125, 125, 125)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatsCPUBound)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatsThroughput))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatsCicloActual)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(lblStatsTotales)
                    .addComponent(lblStatsCPUBound)
                    .addComponent(lblStatsThroughput))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(lblStatsIOBound)
                    .addComponent(lblStatsCicloActual))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EstadisticasLayout = new javax.swing.GroupLayout(Estadisticas);
        Estadisticas.setLayout(EstadisticasLayout);
        EstadisticasLayout.setHorizontalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EstadisticasLayout.setVerticalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 545, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estadisticas", Estadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProcesoActionPerformed
        // TODO add your handling code here:
        try {
                // 1. Leer datos comunes de la interfaz
                int id = so.getProcessCounter(); // Usamos un getter ahora (lo crearemos)
                String nombreManual = txtNombre.getText(); // Leemos el nombre

                // Validar que el nombre no esté vacío
                if (nombreManual == null || nombreManual.trim().isEmpty()) {
                    // Si está vacío, usamos el contador automático del SO
                    // (No hacemos nada aquí, el SO ya genera P + contador)
                } else {
                     // Si el usuario escribió algo, intentamos usarlo
                     // Necesitaríamos un método en SO para esto, ej: so.setNextProcessName(nombreManual)
                     // Por simplicidad ahora, lo ignoramos y dejamos que SO use P + contador
                     // O podrías modificar el constructor de Proceso/SO para aceptarlo
                }

                int instrucciones = (int) spinnerInstrucciones.getValue();

                // --- VALORES FIJOS TEMPORALES (¡DEBERÍAS AÑADIR SPINNERS PARA ESTOS!) ---
                int tamano = 20; // Tamaño fijo temporal
                long tiempoESFijo = 5L; // Tiempo ES fijo temporal (usado por CPU Bound)
                int prioridad = 0; // Prioridad fija temporal
                // --- FIN VALORES FIJOS ---

                // Determinar tipo
                String tipoStr = (String) comboTipo.getSelectedItem();
                Proceso.Tipo tipo;
                if (tipoStr.equals("CPU bound")) {
                    tipo = Proceso.Tipo.CPU_BOUND;
                } else if (tipoStr.equals("I/O bound")) {
                    tipo = Proceso.Tipo.IO_BOUND;
                } else {
                    tipo = Proceso.Tipo.NORMAL; // Asumimos Normal si no es ninguno
                }

                // 2. Llamar al método crearProceso adecuado
                if (tipo == Proceso.Tipo.IO_BOUND) {
                    // Leer valores específicos de I/O Bound
                    int instParaES = (int) spinnerCiclosExcepcion.getValue();
                    int ciclosParaES = (int) spinnerCiclosSatisfacer.getValue();

                    // Llamar a la versión IO Bound de crearProceso
                    so.crearProceso(id, tipo, instrucciones, tamano, 0, prioridad, instParaES, ciclosParaES); 
                    // Nota: Pasé 0 como tiempoES porque este constructor no lo usa directamente para I/O

                } else { 
                    // Para CPU_BOUND o NORMAL
                    // Llamar a la versión NO IO Bound de crearProceso
                    so.crearProceso(id, tipo, instrucciones, tamano, tiempoESFijo, prioridad);
                }

                // Limpiar campo de nombre después de crear (opcional)
                txtNombre.setText(""); 

            } catch (Exception e) {
                // Mostrar un error si algo sale mal
                javax.swing.JOptionPane.showMessageDialog(this, "Error al crear proceso: " + e.getMessage());
                e.printStackTrace(); // Imprime más detalles del error en la consola
            }
    }//GEN-LAST:event_btnCrearProcesoActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        String politicaSeleccionada = (String) comboPolitica.getSelectedItem();
        ISchedulingAlgorithm nuevoAlgoritmo;

        switch (politicaSeleccionada) {
            case "FCFS":
                nuevoAlgoritmo = new FIFOScheduling();
                break;
            case "Round Robin":
                nuevoAlgoritmo = new RRScheduling();
                break;
            case "SPN":
                nuevoAlgoritmo = new SPNScheduling();
                break;
            case "SRT":
                nuevoAlgoritmo = new SRTScheduling();
                break;
            case "HRRN":
                nuevoAlgoritmo = new HRRNScheduling();
                break;
            case "Feedback":
                nuevoAlgoritmo = new FeedbackScheduling();
                break;
            default:
                nuevoAlgoritmo = new FIFOScheduling(); // Default
        }

        // Llama al método del SO que ya existe
        so.setAlgoritmo(nuevoAlgoritmo); 

        // Ajusta el quantum de la CPU según el algoritmo
        if (nuevoAlgoritmo.hasQuantum()) {
            so.setCPUQuantum(5); // 5 Ticks por defecto, puedes hacerlo configurable
        } else {
            so.setCPUQuantum(0); // 0 significa sin quantum
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
// Verifica si el estado del item cambió (fue seleccionado o deseleccionado)
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String tipoSeleccionado = (String) comboTipo.getSelectedItem();

            boolean esIOBound = tipoSeleccionado.equals("I/O bound");

            // Habilita o deshabilita los spinners basados en la selección
            spinnerCiclosExcepcion.setEnabled(esIOBound);
            spinnerCiclosSatisfacer.setEnabled(esIOBound);
        } 
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void btnAplicarDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDuracionActionPerformed
        // TODO add your handling code here:
        try {
            // Leer el valor del spinner
            int nuevoTiempoMs = (int) spinnerDuracionCiclo.getValue();

            // Validar (aunque el spinner ya tiene límites, una doble verificación es buena)
            if (nuevoTiempoMs > 0) {
                // Llamar al método del SO para aplicar el cambio
                so.setDuracionCiclo(nuevoTiempoMs);
                guardarConfiguracionCompleta();
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "La duración debe ser mayor que cero.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al aplicar duración: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAplicarDuracionActionPerformed

    private void btnGuardarDefaultsProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDefaultsProcesoActionPerformed
        // TODO add your handling code here:
        
        guardarConfiguracionCompleta(); // Simplemente llama al método que guarda todo
        
    }//GEN-LAST:event_btnGuardarDefaultsProcesoActionPerformed

    /**
     * @param args the command line arguments
     */

    // En SimuladorGUI.java

public void actualizarGUI() {
    // 1. Actualizar Reloj
    lblRelojGlobal.setText(String.valueOf(so.getClock().getTic()));

    // 2. Actualizar CPU
    Proceso pCPU = so.getCpu().getProcesoActual();
    if (pCPU != null) {
        lblCpuProceso.setText(pCPU.getNombre());
        lblCpuID.setText(String.valueOf(pCPU.getId()));
        lblCpuPC.setText(String.valueOf(pCPU.getProgramCounter()));
        lblCpuMAR.setText(String.valueOf(pCPU.getMemoryAddressRegister()));
        lblCpuStatus.setText(pCPU.getEstado().toString());
        lblCpuTipo.setText(pCPU.getTipo().toString());
    } else {
        lblCpuProceso.setText("N/A");
        lblCpuID.setText("N/A");
        lblCpuPC.setText("N/A");
        lblCpuMAR.setText("N/A");
        lblCpuStatus.setText("IDLE");
        lblCpuTipo.setText("N/A");
    }

    // 3. Actualizar Colas (usando el método fácil de JTextArea)
    actualizarAreaCola(so.getColaListos(), areaListos);
    actualizarAreaCola(so.getColaBloqueados(), areaBloqueados);
    actualizarAreaCola(so.getColaTerminados(), areaTerminados);
    
    // 4. Actualizar Estadísticas
    long cicloActual = so.getClock().getTic();
    int terminadosTotales = so.getStatProcesosTotalesTerminados();

    lblStatsTotales.setText(String.valueOf(terminadosTotales));
    lblStatsIOBound.setText(String.valueOf(so.getStatIoBoundTerminados()));
    lblStatsCPUBound.setText(String.valueOf(so.getStatCpuBoundTerminados()));
    lblStatsCicloActual.setText(String.valueOf(cicloActual));

    // Calcular Throughput (Procesos / Ticks)
    // El PDF pide "Procesos completados por unidad de tiempo" [cite: 23]
    if (cicloActual > 0) {
        double throughput = (double) terminadosTotales / cicloActual;
        // Formatear a 6 decimales
        lblStatsThroughput.setText(String.format("%.6f", throughput));
    } else {
        lblStatsThroughput.setText("0.0");
    }
    
    if (jTabbedPane1.getSelectedComponent() == panelGrafico.getParent()) {
     actualizarGraficoThroughput();
    }
    
}

// Method to load configuration from config.json
private void cargarConfiguracion() {
    SimConfig config = null;
    Gson gson = new Gson();

    // Try to read the config.json file
    try (FileReader reader = new FileReader("config.json")) {
        config = gson.fromJson(reader, SimConfig.class);
        System.out.println("Configuration loaded from config.json");
    } catch (IOException e) {
        System.err.println("Could not load config.json (using defaults): " + e.getMessage());
        // File not found or error reading, create a default config
        config = new SimConfig(); // Uses the default 500ms
    }

        // Apply the loaded (or default) configuration
    if (config != null) {
        // --- Aplicar Duración Ciclo (como antes) ---
        long loadedDuration = config.getDuracionCicloMs();
        spinnerDuracionCiclo.setValue((int) loadedDuration);
        if (so != null) {
            so.setDuracionCiclo(loadedDuration);
        }

        // --- Aplicar Defaults de Creación de Proceso ---
        spinnerInstrucciones.setValue(config.getDefaultInstrucciones());
        comboTipo.setSelectedItem(config.getDefaultTipoProceso());
        spinnerCiclosExcepcion.setValue(config.getDefaultCiclosGenExcepcion());
        spinnerCiclosSatisfacer.setValue(config.getDefaultCiclosSatExcepcion());

        // Asegurarse que los spinners de E/S se habiliten/deshabiliten correctamente
        boolean esIOBound = config.getDefaultTipoProceso().equals("I/O bound");
        spinnerCiclosExcepcion.setEnabled(esIOBound);
        spinnerCiclosSatisfacer.setEnabled(esIOBound);

    } else {
         // Si config es null (error grave), podrías poner valores fijos aquí
         System.err.println("Error crítico: config object es null en cargarConfiguracion.");
         spinnerDuracionCiclo.setValue(500);
         spinnerInstrucciones.setValue(10);
         comboTipo.setSelectedItem("CPU bound");
         spinnerCiclosExcepcion.setValue(5);
         spinnerCiclosSatisfacer.setValue(10);
         spinnerCiclosExcepcion.setEnabled(false);
         spinnerCiclosSatisfacer.setEnabled(false);
    }
}

// Guarda TODA la configuración actual (ciclo + defaults de proceso) en config.json
private void guardarConfiguracionCompleta() {
    SimConfig config = new SimConfig(); // Crea un objeto nuevo

    try {
        // Leer duración del ciclo
        config.setDuracionCicloMs((int) spinnerDuracionCiclo.getValue());

        // Leer defaults de creación de proceso
        config.setDefaultInstrucciones((int) spinnerInstrucciones.getValue());
        config.setDefaultTipoProceso((String) comboTipo.getSelectedItem());
        config.setDefaultCiclosGenExcepcion((int) spinnerCiclosExcepcion.getValue());
        config.setDefaultCiclosSatExcepcion((int) spinnerCiclosSatisfacer.getValue());

    } catch (Exception e) {
        System.err.println("Error leyendo valores de la GUI para guardar config: " + e.getMessage());
        // Podrías mostrar un error al usuario aquí
        javax.swing.JOptionPane.showMessageDialog(this, "Error al leer valores para guardar: " + e.getMessage(), "Error Guardando Config", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // No guardar si hay error leyendo
    }

    // Guardar a JSON (igual que antes)
    Gson gson = new GsonBuilder().setPrettyPrinting().create();
    String jsonString = gson.toJson(config);

    try (FileWriter writer = new FileWriter("config.json")) {
        writer.write(jsonString);
        System.out.println("Configuración completa guardada en config.json");
        // Opcional: Mostrar mensaje de éxito al usuario
        // javax.swing.JOptionPane.showMessageDialog(this, "Defaults guardados.");
    } catch (IOException e) {
        System.err.println("Error guardando configuración completa en config.json: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Error guardando archivo de configuración:\n" + e.getMessage(), "Config Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

// Método ayudante para no repetir código
private void actualizarAreaCola(Cola cola, javax.swing.JTextArea area) {
    StringBuilder sb = new StringBuilder();

    // Usamos el .forEach() que ya tiene tu clase Cola
    cola.forEach(p -> {
        sb.append("ID: ").append(p.getId())
          .append(" | Nombre: ").append(p.getNombre())
          .append(" | PC: ").append(p.getProgramCounter())
          .append(" | Estado: ").append(p.getEstado().toString())
          .append("\n");
    });

    area.setText(sb.toString());
    area.setCaretPosition(0); // Para que el scroll se vaya al inicio
}

private void actualizarGraficoThroughput() {
    // 1. Crear el set de datos para el gráfico de barras
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    // 2. Añadir los datos
    // NOTA: ¡Esto necesita la lógica de backend de "estadísticas por política"!
    // Por ahora, usaremos datos de ejemplo y el throughput general.
    // Cuando tengas las estadísticas por política, podrás reemplazar esto.

    double throughputGeneral = 0.0;
    if (so.getClock().getTic() > 0) {
        throughputGeneral = (double) so.getStatProcesosTotalesTerminados() / so.getClock().getTic();
    }

    // (Datos de ejemplo)
    dataset.addValue(throughputGeneral, "Throughput", "FCFS");
    dataset.addValue(0.0, "Throughput", "Round Robin");
    dataset.addValue(0.0, "Throughput", "SPN");
    dataset.addValue(0.0, "Throughput", "SRT");
    dataset.addValue(0.0, "Throughput", "HRRN");

    // 3. Crear el gráfico de barras
    JFreeChart barChart = ChartFactory.createBarChart(
        "Comparación de Throughputs", // Título del gráfico
        "Política",                   // Etiqueta eje X
        "Throughput",                 // Etiqueta eje Y
        dataset                       // Los datos
    );

    // 4. Crear el panel que contiene el gráfico
    ChartPanel chartPanel = new ChartPanel(barChart);

    // 5. Añadir el panel del gráfico a nuestro 'panelGrafico' del diseñador
    panelGrafico.removeAll(); // Limpia el panel por si había un gráfico anterior
    panelGrafico.add(chartPanel, BorderLayout.CENTER); // Añade el nuevo
    panelGrafico.validate(); // Refresca el panel
}

    public javax.swing.JTextArea getAreaLog() {
        return areaLog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Configuracion;
    private javax.swing.JPanel Estadisticas;
    private javax.swing.JPanel Graficos;
    private javax.swing.JPanel Simulador;
    private javax.swing.JTextArea areaBloqueados;
    private javax.swing.JTextArea areaListos;
    private javax.swing.JTextArea areaLog;
    private javax.swing.JTextArea areaTerminados;
    private javax.swing.JButton btnAplicarDuracion;
    private javax.swing.JButton btnCrearProceso;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnGuardarDefaultsProceso;
    private javax.swing.JComboBox<String> comboPolitica;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCpuID;
    private javax.swing.JLabel lblCpuMAR;
    private javax.swing.JLabel lblCpuPC;
    private javax.swing.JLabel lblCpuProceso;
    private javax.swing.JLabel lblCpuStatus;
    private javax.swing.JLabel lblCpuTipo;
    private javax.swing.JLabel lblRelojGlobal;
    private javax.swing.JLabel lblStatsCPUBound;
    private javax.swing.JLabel lblStatsCicloActual;
    private javax.swing.JLabel lblStatsIOBound;
    private javax.swing.JLabel lblStatsThroughput;
    private javax.swing.JLabel lblStatsTotales;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JSpinner spinnerCiclosExcepcion;
    private javax.swing.JSpinner spinnerCiclosSatisfacer;
    private javax.swing.JSpinner spinnerDuracionCiclo;
    private javax.swing.JSpinner spinnerInstrucciones;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
